//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWebApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int ID { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public int IDCabinet { get; set; }
        public int IDSpecializations { get; set; }
        public Nullable<int> IDArea { get; set; }

        [JsonIgnore]
        public virtual Area Area { get; set; }
        [JsonIgnore]
        public virtual Cabinet Cabinet { get; set; }
        [JsonIgnore]
        public virtual Specializations Specializations { get; set; }

       

    }
}
