//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWebApi.Models
{
    using Newtonsoft.Json;
    
    public partial class Patient
    {
        public int ID { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfBirthday { get; set; }
        public int IDGender { get; set; }
        public int IDArea { get; set; }

        [JsonIgnore]
        public virtual Area Area { get; set; }
        [JsonIgnore]
        public virtual Gender Gender { get; set; }

        

    }
}
